# arduinoData = serial.Serial('/dev/ttyUSB0', '9600')
class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		self.arm = None
		self.pos1 = 1200
		self.pos2 = 1350
		self.pos3 = 1350
		self.pos4 = 1150
		self.pos5 = 1150
		self.pos6 = 1150
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1080, 720)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
		MainWindow.setSizePolicy(sizePolicy)
		MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
		MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.label = QtWidgets.QLabel(self.centralwidget)
		self.label.setGeometry(QtCore.QRect(0, 0, 1080, 720))
		self.label.setMinimumSize(QtCore.QSize(1080, 720))
		self.label.setMaximumSize(QtCore.QSize(1080, 720))
		self.label.setText("")
		self.label.setPixmap(QtGui.QPixmap("arm1.png"))
		self.label.setObjectName("label")
		self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
		self.lcdNumber.setGeometry(QtCore.QRect(780, 580, 131, 51))
		self.lcdNumber.setObjectName("lcdNumber")
		self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
		self.verticalSlider.setGeometry(QtCore.QRect(830, 130, 61, 441))
		self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
		self.verticalSlider.setObjectName("verticalSlider_2")
		self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksRight)
		self.verticalSlider.setTickInterval(1)
		self.verticalSlider.valueChanged.connect(self.valuechange)
		self.verticalSlider.setMinimum(-60)
		self.verticalSlider.setMaximum(60)
		self.label_1 = QtWidgets.QLabel(self.centralwidget)
		self.label_1.setGeometry(QtCore.QRect(250, 520, 41, 41))
		self.label_1.setText("")
		self.label_1.setPixmap(QtGui.QPixmap("green_dot.png"))
		self.label_1.setScaledContents(True)
		self.label_1.setObjectName("label_1")
		self.label_1.setHidden(True)
		self.label_2 = QtWidgets.QLabel(self.centralwidget)
		self.label_2.setGeometry(QtCore.QRect(250, 450, 41, 41))
		self.label_2.setText("")
		self.label_2.setPixmap(QtGui.QPixmap("green_dot.png"))
		self.label_2.setScaledContents(True)
		self.label_2.setObjectName("label_2")
		self.label_2.setHidden(True)
		self.label_3 = QtWidgets.QLabel(self.centralwidget)
		self.label_3.setGeometry(QtCore.QRect(300, 160, 41, 41))
		self.label_3.setText("")
		self.label_3.setPixmap(QtGui.QPixmap("green_dot.png"))
		self.label_3.setScaledContents(True)
		self.label_3.setObjectName("label_3")
		self.label_3.setHidden(True)
		self.label_4 = QtWidgets.QLabel(self.centralwidget)
		self.label_4.setGeometry(QtCore.QRect(50, 240, 41, 41))
		self.label_4.setText("")
		self.label_4.setPixmap(QtGui.QPixmap("green_dot.png"))
		self.label_4.setScaledContents(True)
		self.label_4.setObjectName("label_4")
		self.label_4.setHidden(True)
		self.label_5 = QtWidgets.QLabel(self.centralwidget)
		self.label_5.setGeometry(QtCore.QRect(480, 30, 41, 41))
		self.label_5.setText("")
		self.label_5.setPixmap(QtGui.QPixmap("green_dot.png"))
		self.label_5.setScaledContents(True)
		self.label_5.setObjectName("label_5")
		self.label_5.setHidden(True)
		self.label_6 = QtWidgets.QLabel(self.centralwidget)
		self.label_6.setGeometry(QtCore.QRect(300, 70, 41, 41))
		self.label_6.setText("")
		self.label_6.setPixmap(QtGui.QPixmap("green_dot.png"))
		self.label_6.setScaledContents(True)
		self.label_6.setObjectName("label_6")
		self.label_6.setHidden(True)
		self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
		self.pushButton1.setGeometry(QtCore.QRect(250, 520, 41, 41))
		self.pushButton1.setText("")
		self.pushButton1.setObjectName("pushButton1")
		self.pushButton6 = QtWidgets.QPushButton(self.centralwidget)
		self.pushButton6.setGeometry(QtCore.QRect(480, 30, 41, 41))
		self.pushButton6.setText("")
		self.pushButton6.setObjectName("pushButton2")
		self.pushButton5 = QtWidgets.QPushButton(self.centralwidget)
		self.pushButton5.setGeometry(QtCore.QRect(300, 70, 41, 41))
		self.pushButton5.setText("")
		self.pushButton5.setObjectName("pushButton3")
		self.pushButton4 = QtWidgets.QPushButton(self.centralwidget)
		self.pushButton4.setGeometry(QtCore.QRect(300, 160, 41, 41))
		self.pushButton4.setText("")
		self.pushButton4.setObjectName("pushButton4")
		self.pushButton3 = QtWidgets.QPushButton(self.centralwidget)
		self.pushButton3.setGeometry(QtCore.QRect(50, 240, 41, 41))
		self.pushButton3.setText("")
		self.pushButton3.setObjectName("pushButton5")
		self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
		self.pushButton2.setGeometry(QtCore.QRect(250, 450, 41, 41))
		self.pushButton2.setText("")
		self.pushButton2.setObjectName("pushButton6")
		self.up = QtWidgets.QPushButton(self.centralwidget)
		self.up.setGeometry(QtCore.QRect(780, 580, 40, 50))
		self.up.setText("")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap("up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.up.setIcon(icon1)
		self.up.setIconSize(QtCore.QSize(32,32))
		self.up.setObjectName("up")
		self.r = QtWidgets.QPushButton(self.centralwidget)
		self.r.setGeometry(QtCore.QRect(740, 580, 40, 50))
		self.r.setText("")
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap("Background.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.r.setIcon(icon2)
		self.r.setIconSize(QtCore.QSize(32,32))
		self.r.setObjectName("reset")
		self.label.raise_()
		self.verticalSlider.raise_()
		self.lcdNumber.raise_()
		self.pushButton1.raise_()
		self.label_1.raise_()
		self.pushButton2.raise_()
		self.pushButton3.raise_()
		self.pushButton4.raise_()
		self.pushButton5.raise_()
		self.pushButton6.raise_()
		self.up.raise_()
		self.r.raise_()
		self.label_2.raise_()
		self.label_4.raise_()
		self.label_3.raise_()
		self.label_6.raise_()
		self.label_5.raise_()
		MainWindow.setCentralWidget(self.centralwidget)
		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)
		self.pushButton1.clicked.connect(self.amr1)
		self.pushButton2.clicked.connect(self.amr2)
		self.pushButton3.clicked.connect(self.amr3)
		self.pushButton4.clicked.connect(self.amr4)
		self.pushButton5.clicked.connect(self.amr5)
		self.pushButton6.clicked.connect(self.amr6)
		self.up.clicked.connect(self.upload)
		self.r.clicked.connect(self.reset)
	def reset(self):
		# arduinoData.write(text.encode())
		print("reset")
	def upload(self):
		text = None
		if self.arm == 1:
		text= str(self.arm)+str(self.pos1)+str(self.size)
		self.pos1 = self.size
		elif self.arm == 2:
		text= str(self.arm)+str(self.pos2)+str(self.size)
		self.pos2 = self.size
		elif self.arm == 3:
		text= str(self.arm)+str(self.pos3)+str(self.size)
		self.pos3 = self.size
		elif self.arm == 4:
		text= str(self.arm)+str(self.pos4)+str(self.size)
		self.pos4 = self.size
		elif self.arm == 5:
		text= str(self.arm)+str(self.pos5)+str(self.size)
		self.pos5 = self.size
		elif self.arm == 6:
		text= str(self.arm)+str(self.pos6)+str(self.size)
		self.pos6 = self.size
		print("sending data ",text)
	# arduinoData.write(text.encode())
	def valuechange(self):
		self.size = self.verticalSlider.value()
		self.lcdNumber.display(self.size)
		# print(self.size)
	def mapped(x, in_min, in_max, out_min, out_max):
		return int((x - in_min) * (out_max - out_min) / (in_max - in_min) + out_min)
		self.size = mapped(self.size, -60, 60, 600, 1800)
		if self.size < 1000:
		self.size = '0'+str(self.size)
	def amr1(self):
		print("arm1")
		self.arm = 1
		# arduinoData.write(str(self.arm).encode())
		self.label_1.setHidden(False)
		self.label_2.setHidden(True)
		self.label_3.setHidden(True)
		self.label_4.setHidden(True)
		self.label_5.setHidden(True)
		self.label_6.setHidden(True)
	def amr2(self):
		print("arm2")
		self.arm = 2
		#arduinoData.write(str(self.arm).encode())
		self.label_1.setHidden(True)
		self.label_2.setHidden(False)
		self.label_3.setHidden(True)
		self.label_4.setHidden(True)
		self.label_5.setHidden(True)
		self.label_6.setHidden(True)
	def amr3(self):
		print("arm3")
		self.arm = 3
		#arduinoData.write(str(self.arm).encode())
		self.label_1.setHidden(True)
		self.label_2.setHidden(True)
		self.label_4.setHidden(False)
		self.label_3.setHidden(True)
		self.label_5.setHidden(True)
		self.label_6.setHidden(True)
	def amr4(self):
		print("arm4")
		self.arm = 4
		#arduinoData.write(str(self.arm).encode())
		self.label_1.setHidden(True)
		self.label_2.setHidden(True)
		self.label_4.setHidden(True)
		self.label_3.setHidden(False)
		self.label_5.setHidden(True)
		self.label_6.setHidden(True)
	def amr5(self):
		print("arm5")
		self.arm = 5
		#arduinoData.write(str(self.arm).encode())
		self.label_1.setHidden(True)
		self.label_2.setHidden(True)
		self.label_3.setHidden(True)
		self.label_4.setHidden(True)
		self.label_6.setHidden(False)
		self.label_5.setHidden(True)
	def amr6(self):
		print("arm6")
		self.arm = 6
		#arduinoData.write(str(self.arm).encode())
		self.label_1.setHidden(True)
		self.label_2.setHidden(True)
		self.label_3.setHidden(True)
		self.label_4.setHidden(True)
		self.label_6.setHidden(True)
		self.label_5.setHidden(False)
	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "arm"))
if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())