# arduinoData = serial.Serial('/dev/ttyACMO', '9600')
class Ui_MainWindow(object):
	def setupUi(self, MainWindow):
		self.speed = 70
		MainWindow.setObjectName("MainWindow")
		MainWindow.resize(1080, 720)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
		MainWindow.setSizePolicy(sizePolicy)
		MainWindow.setMinimumSize(QtCore.QSize(1080, 720))
		MainWindow.setMaximumSize(QtCore.QSize(1080, 720))
		self.centralwidget = QtWidgets.QWidget(MainWindow)
		self.centralwidget.setObjectName("centralwidget")
		self.down = QtWidgets.QPushButton(self.centralwidget)
		self.down.setGeometry(QtCore.QRect(425, 450, 230, 160))
		self.down.setText("")
		icon = QtGui.QIcon()
		icon.addPixmap(QtGui.QPixmap("down.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.down.setIcon(icon)
		self.down.setIconSize(QtCore.QSize(128, 128))
		self.down.setObjectName("down")
		self.up = QtWidgets.QPushButton(self.centralwidget)
		self.up.setGeometry(QtCore.QRect(425, 60, 230, 160))
		self.up.setText("")
		icon1 = QtGui.QIcon()
		icon1.addPixmap(QtGui.QPixmap("up.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.up.setIcon(icon1)
		self.up.setIconSize(QtCore.QSize(128, 128))
		self.up.setObjectName("up")
		self.left = QtWidgets.QPushButton(self.centralwidget)
		self.left.setGeometry(QtCore.QRect(160, 240, 230, 160))
		self.left.setAutoFillBackground(False)
		self.left.setText("")
		icon2 = QtGui.QIcon()
		icon2.addPixmap(QtGui.QPixmap("left.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.left.setIcon(icon2)
		self.left.setIconSize(QtCore.QSize(128, 128))
		self.left.setObjectName("left")
		self.right = QtWidgets.QPushButton(self.centralwidget)
		self.right.setGeometry(QtCore.QRect(690, 240, 230, 160))
		self.right.setText("")
		icon3 = QtGui.QIcon()
		icon3.addPixmap(QtGui.QPixmap("right.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.right.setIcon(icon3)
		self.right.setIconSize(QtCore.QSize(128, 128))
		self.right.setObjectName("right")
		self.verticalSlider = QtWidgets.QSlider(self.centralwidget)
		self.verticalSlider.setGeometry(QtCore.QRect(40, 280, 61, 350))
		self.verticalSlider.setOrientation(QtCore.Qt.Vertical)
		self.verticalSlider.setObjectName("verticalSlider")
		self.verticalSlider.setMinimum(0)
		self.verticalSlider.setMaximum(140)
		self.verticalSlider.setTickPosition(QtWidgets.QSlider.TicksRight)
		self.verticalSlider.setTickInterval(5)
		self.verticalSlider.valueChanged.connect(self.valuechange)
		self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
		self.lcdNumber.setGeometry(QtCore.QRect(0, 630, 120, 51))
		self.lcdNumber.setObjectName("lcdNumber")
		self.stop = QtWidgets.QPushButton(self.centralwidget)
		self.stop.setGeometry(QtCore.QRect(910, 570, 131, 91))
		self.stop.setText("")
		icon4 = QtGui.QIcon()
		icon4.addPixmap(QtGui.QPixmap("stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
		self.stop.setIcon(icon4)
		self.stop.setIconSize(QtCore.QSize(128, 128))
		self.stop.setObjectName("pushButton")
		MainWindow.setCentralWidget(self.centralwidget)
		self.statusbar = QtWidgets.QStatusBar(MainWindow)
		self.statusbar.setObjectName("statusbar")
		MainWindow.setStatusBar(self.statusbar)
		self.up.clicked.connect(self.forward)
		self.down.clicked.connect(self.backward)
		self.left.clicked.connect(self.leftward)
		self.right.clicked.connect(self.rightward)
		self.stop.clicked.connect(self.allstop)
		self.retranslateUi(MainWindow)
		QtCore.QMetaObject.connectSlotsByName(MainWindow)
	def valuechange(self):
		self.size = self.verticalSlider.value()
		self.lcdNumber.display(self.size)
		# print(self.size)
	def forward(self):
		print("forward") # do something with the button clicked
		# arduinoData.write('x')
	def backward(self):
		print("backward") # do something with the button clicked
	def rightward(self):
		print("rightward") # do something with the button clicked
	def leftward(self):
		print("leftward") # do something with the button clicked
	def allstop(self):
		print("stop") # do something with the button clicked
	def retranslateUi(self, MainWindow):
		_translate = QtCore.QCoreApplication.translate
		MainWindow.setWindowTitle(_translate("MainWindow", "ROVER"))
if __name__ == "__main__":
	import sys
	app = QtWidgets.QApplication(sys.argv)
	MainWindow = QtWidgets.QMainWindow()
	ui = Ui_MainWindow()
	ui.setupUi(MainWindow)
	MainWindow.show()
	sys.exit(app.exec_())